# Generated by Django 5.0.3 on 2024-04-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_naem',
            new_name='first_name',
        ),
    ]
